name: app-server
region: sfo
services:
- dockerfile_path: Dockerfile
  envs:
  - key: APP_APPLICATION__BASE_URL
    scope: RUN_TIME
    value: ${APP_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: intrepion/intrepion-saying-hello-json-rpc-server-rust-actix-web
  health_check:
    http_path: /health_check
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: server
  routes:
  - path: /
  source_dir: /
